language: python
python:
- 2.7
env:
#- ZMQ_VERSION=
- ZMQ_VERSION=4.1.0-rc1
# - ZMQ_VERSION=4.0.5
# - ZMQ_VERSION=4.0.4
# - ZMQ_VERSION=4.0.3
# - ZMQ_VERSION=4.0.2
# - ZMQ_VERSION=4.0.1
# - ZMQ_VERSION=3.2.4
# - ZMQ_VERSION=3.2.3
# - ZMQ_VERSION=3.2.2
# - ZMQ_VERSION=2.2.0
# - ZMQ_VERSION=2.1.11
# - ZMQ_VERSION=2.1.10
# - ZMQ_VERSION=2.1.9
# - ZMQ_VERSION=2.1.7
# - ZMQ_VERSION=2.1.4
matrix:
  allow_failures:
  - env: ZMQ_VERSION=
before_install:
- |
  pwd
  ls
- | # install zeromq
  if [ $ZMQ_VERSION ]
  then
    if [[ $ZMQ_VERSION == 2.* ]]
    then
      sudo apt-get install uuid-dev
    fi
    wget http://download.zeromq.org/zeromq-$ZMQ_VERSION.tar.gz
    tar xvzf zeromq-$ZMQ_VERSION.tar.gz
    cd zeromq-$ZMQ_VERSION
  else
    sudo apt-get install libtool
    git clone https://github.com/zeromq/libzmq.git libzmq
    cd libzmq
    ./autogen.sh
  fi
  ./configure --with-pgm --prefix=`pwd`/../local
  make
  make install
  cd ..
- | # install pyzmq
  pip install cython
  git clone -b v14.3.1 https://github.com/zeromq/pyzmq.git pyzmq
  cd pyzmq
  python setup.py clean
  python setup.py configure --zmq=`pwd`/../local
  python setup.py build_ext --inplace
  ls
  pip install -e .
  cd ..
install:
- pip install -e .
- pip install pytest psutil pylru pytest-cov coveralls
script:
- py.test -v --inproc --ipc --tcp --epgm --incremental-patience --cov=zeronimo
after_success:
- coveralls
