language: python
python:
- 2.7
env:
- ZMQ_VERSION=4.0.4
- ZMQ_VERSION=4.0.3
- ZMQ_VERSION=4.0.2
- ZMQ_VERSION=4.0.1
- ZMQ_VERSION=3.2.4
- ZMQ_VERSION=3.2.3
- ZMQ_VERSION=3.2.2
- ZMQ_VERSION=2.2.0
- ZMQ_VERSION=2.1.11
- ZMQ_VERSION=2.1.10
- ZMQ_VERSION=2.1.9
- ZMQ_VERSION=2.1.7
- ZMQ_VERSION=2.1.4
before_install:
# cython, pytest, psutil
- pip install cython pytest psutil
# libcap2-bin, uuid-dev
- sudo apt-get install libcap2-bin uuid-dev
# zeromq
- wget http://download.zeromq.org/zeromq-$ZMQ_VERSION.tar.gz
- tar xvzf zeromq-$ZMQ_VERSION.tar.gz
- cd zeromq-$ZMQ_VERSION
- ./configure --with-pgm --prefix=`pwd`/../local
- make
- make install
- cd ..
# pyzmq-14.1.1
- git clone https://github.com/zeromq/pyzmq.git pyzmq
- cd pyzmq
- git checkout v14.1.1
- python setup.py clean
- python setup.py configure --zmq=../local
- python setup.py build_ext --inplace
- pip install -e .
- cd ..
install:
- pip install -e .
before_script:
# make sure to use PGM
- sudo setcap CAP_NET_RAW=ep `readlink -f \`which python\``
script:
- py.test -v --all --incremental-patience
