language: python
python:
- 2.7
env:
- ZMQ_VERSION=4.0.4
- ZMQ_VERSION=3.2.4
- ZMQ_VERSION=2.2.0
before_install:
# zeromq
- wget http://download.zeromq.org/zeromq-$ZMQ_VERSION.tar.gz
- tar xvzf zeromq-$ZMQ_VERSION.tar.gz
- cd zeromq-$ZMQ_VERSION
- ./configure --with-pgm --prefix=`pwd`/../local
- make
- make install
- cd ..
# cython, pytest
- pip install cython pytest
# pyzmq-14.1.1
- git clone https://github.com/zeromq/pyzmq.git pyzmq
- cd pyzmq
- git checkout v14.1.1
- python setup.py clean
- python setup.py configure --zmq=../local
- python setup.py build_ext --inplace
- pip install -e .
- cd ..
# libcap2-bin
- sudo apt-get install libcap2-bin
install:
- pip install -e .
before_script:
- sudo setcap CAP_NET_RAW=ep `which python`
script:
- py.test -v --all
