language: python
python:
- 2.7
- pypy
env:
  global:
  # Target versions:
  - ZMQ_VERSION=4.1.5
  - PYZMQ_VERSION=15.4.0
  matrix:
  -
  # The latest versions under development:
  - PYZMQ_VERSION=
  - ZMQ_VERSION=
  - PYZMQ_VERSION= ZMQ_VERSION=
  # Older PyZMQ versions:
  - PYZMQ_VERSION=15.3.0
  - PYZMQ_VERSION=15.2.0
  - PYZMQ_VERSION=15.1.0
  - PYZMQ_VERSION=15.0.0
  - PYZMQ_VERSION=14.7.0
  - PYZMQ_VERSION=14.6.0
  - PYZMQ_VERSION=14.5.0
  - PYZMQ_VERSION=14.4.1
  - PYZMQ_VERSION=14.4.0
  - PYZMQ_VERSION=14.3.1
  - PYZMQ_VERSION=14.3.0
  - PYZMQ_VERSION=14.2.0
  - PYZMQ_VERSION=14.1.0
  - PYZMQ_VERSION=14.0.1
  - PYZMQ_VERSION=14.0.0
  # Older ZeroMQ versions:
  - ZMQ_VERSION=4.1.4
  - ZMQ_VERSION=4.1.3
  - ZMQ_VERSION=4.1.2
  - ZMQ_VERSION=4.1.1
  - ZMQ_VERSION=4.1.0-rc1
  - ZMQ_VERSION=4.0.8
  - ZMQ_VERSION=4.0.7
  - ZMQ_VERSION=4.0.6
  - ZMQ_VERSION=4.0.5
  - ZMQ_VERSION=4.0.4
  - ZMQ_VERSION=4.0.3
  - ZMQ_VERSION=4.0.2
  - ZMQ_VERSION=4.0.1
  - ZMQ_VERSION=3.2.5
  - ZMQ_VERSION=3.2.4
  - ZMQ_VERSION=3.2.3
  - ZMQ_VERSION=3.2.2
  - ZMQ_VERSION=2.2.0
  - ZMQ_VERSION=2.1.11
  - ZMQ_VERSION=2.1.10
  - ZMQ_VERSION=2.1.9
  - ZMQ_VERSION=2.1.8-rc
  - ZMQ_VERSION=2.1.7
  - ZMQ_VERSION=2.1.4
  # Broken ZeroMQ versions:
  # - ZMQ_VERSION=2.1.6
  # - ZMQ_VERSION=2.1.5
  # PyZMQ supports only >=2.1.4, >=3.2.2, >=4.0.1, and >=4.2.0.
  # - ZMQ_VERSION=4.0.0
  # - ZMQ_VERSION=3.2.1
  # - ZMQ_VERSION=3.2.0
  # - ZMQ_VERSION=3.1.0
  # - ZMQ_VERSION=2.1.3
  # - ZMQ_VERSION=2.1.2
  # - ZMQ_VERSION=2.1.1
  # - ZMQ_VERSION=2.1.0
matrix:
  allow_failures:
  - env: PYZMQ_VERSION=
  - env: ZMQ_VERSION=
  - env: PYZMQ_VERSION= ZMQ_VERSION=
before_install:
- set -e
- sudo apt-get update -qq
- ./develop.sh .dev --zmq="$ZMQ_VERSION" --pyzmq="$PYZMQ_VERSION"
install:
- pip install -e $TRAVIS_BUILD_DIR
- pip install pytest pytest-rerunfailures psutil singledispatch
- pip install flake8 pytest-cov coveralls
script:
- |
  cd $TRAVIS_BUILD_DIR
  flake8 zeronimo test.py conftest.py setup.py -v --show-source
  py.test -v --inproc --ipc --tcp --epgm --incremental-patience --cov=zeronimo
after_success:
- coveralls
