language: python
python:
- 2.7
env:
# - ZMQ_VERSION=
# - ZMQ_VERSION=4.1.0-rc1
- ZMQ_VERSION=4.0.5
# - ZMQ_VERSION=4.0.4
# - ZMQ_VERSION=4.0.3
# - ZMQ_VERSION=4.0.2
# - ZMQ_VERSION=4.0.1
# - ZMQ_VERSION=3.2.4
# - ZMQ_VERSION=3.2.3
- ZMQ_VERSION=3.2.2
- ZMQ_VERSION=2.2.0
# - ZMQ_VERSION=2.1.11
# - ZMQ_VERSION=2.1.10
# - ZMQ_VERSION=2.1.9
# - ZMQ_VERSION=2.1.7
# - ZMQ_VERSION=2.1.4
matrix:
  allow_failures:
  - env: ZMQ_VERSION=
before_install:
- | # install zeromq
  cd $TRAVIS_BUILD_DIR
  if [[ "$ZMQ_VERSION" ]]
  then
    if [[ "$ZMQ_VERSION" == 2.* ]]
    then
      sudo apt-get update
      sudo apt-get install uuid-dev
    fi
    mkdir src && cd src
    curl http://download.zeromq.org/zeromq-$ZMQ_VERSION.tar.gz | tar xz
    cd zeromq-*
  else
    sudo apt-get install libtool
    # libsodium
    cd $TRAVIS_BUILD_DIR
    git clone git://github.com/jedisct1/libsodium.git
    cd libsodium
    ./autogen.sh
    ./configure
    make check
    sudo make install
    sudo ldconfig
    # libzmq
    cd $TRAVIS_BUILD_DIR
    git clone https://github.com/zeromq/libzmq.git
    cd libzmq
    ./autogen.sh
  fi
  ./configure --with-pgm --prefix=$TRAVIS_BUILD_DIR/local
  make
  make install
- | # install pyzmq
  cd $TRAVIS_BUILD_DIR
  pip install cython
  git clone -b v14.3.1 https://github.com/zeromq/pyzmq.git pyzmq
  cd pyzmq
  python setup.py clean
  python setup.py configure --zmq=$TRAVIS_BUILD_DIR/local
  python setup.py build_ext --inplace
  pip install -e .
install:
- pip install -e $TRAVIS_BUILD_DIR
- pip install pytest pytest-mock pytest-rerunfailures psutil pylru
- pip install flake8 pytest-cov coveralls
script:
- |
  cd $TRAVIS_BUILD_DIR
  flake8 zeronimo test.py conftest.py setup.py -v --show-source
  py.test -v --inproc --ipc --tcp --epgm --incremental-patience --cov=zeronimo
after_success:
- coveralls
